metadata:
  kind: codefresh
  installer:
    type: helm
    helm:
      chart: ./codefresh-1.0.99-six.tgz
  
kubernetes:
  namespace: codefresh-dev
  context: 
  #kubeconfig:

global:
  ### Codefresh App domain name. appUrl is manadatory parameter
  appUrl: codefresh-dev.v12.np01.ocp.six-group.net
  appProtocol: https

  stepsCatalogOnPremise: true
  stepsCatalogOnPremiseRegistry: artifactory.six-group.net

tls:
  selfSigned: true
  cert: certs/ssl.crt
  key: certs/private.key

images:
  codefreshRegistrySa: sa.json
  usePrivateRegistry: true
  privateRegistry:
    address: artifactory.six-group.net
    username: registry-user
    password: registry-password
  lists:
  - images/images-list-1.0.99

dbinfra:
  enabled: true
  rabbitmq:
    repository: artifactory.six-group.net/rabbitmq
  postgresql:
    repository: artifactory.six-group.net/centos/postgresql-95-centos7
  mongodb:
    repository: artifactory.six-group.net/bitnami/mongodb
  redis:
    repository: artifactory.six-group.net/bitnami/redis

### Includes addional configurations
include:
- values/openshift.yaml